### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by criticalboot** [stephenwvickers/node-net-ping#32]
Working with node, angular & election app, trying to use your module to ping some IP to check the device status.  

`var pingSession = require("net-ping").createSession();`

getting the following Error @ line  raw-socket/index.js: 47

`Operation not permitted`

Please suggest me how to resolve this.

> Process Versions { http_parser: '2.7.0',
>   node: '6.5.0',
>   v8: '5.3.332.47',
>   uv: '1.9.1',
>   zlib: '1.2.8',
>   ares: '1.10.1-DEV',
>   modules: '50',
>   openssl: '1.0.2h',
>   electron: '1.4.10',
>   chrome: '53.0.2785.143',
>   'atom-shell': '1.4.10' }

**Comment by stephenwvickers** [comment]
The error is clear, you do not have the appropriate permissions to perform the operationion.  Specifically, when you attempt to create a raw-socket instance.

**Comment by nickmetal** [comment]
@stephenwvickers which linux group should i add for my user to permit this operation? I down want to use sudo command

**Comment by somec** [comment]
@nickmetal I hope you don't mind me answering since I have had the same problem and got it solved. 

As far as I know, there isn't a  group for it, but you can use setcap on the node executable.

`sudo setcap cap_net_raw+ep /path/to/bin/node`

**CAP_NET_RAW**

- use RAW and PACKET sockets;
- bind to any address for transparent proxying.


**+ep**

- "+" Add the capability ( "-" to remove)
- e:Effective This means the capability is “activated”.
- p: Permitted This means the capability can be used/is allowed.
- i: Inherited The capability is kept by child/subprocesses
